pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
    - id: lint-nodejs
    - id: unit-tests-nodejs
releases:
  published:
    tasks:
      - id: npm-publish
      - id: release-notes
