pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prBodyCheck: true
    - id: lint-nodejs
    - id: unit-tests-nodejs
  notifications:
    all:
      - id: prcomment
pullrequestedit:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prBodyCheck: true
releases:
  published:
    tasks:
      - id: npm-publish
      - id: release-notes
      - id: docker-hub-publish
    notifications:
      all:
        - id: slack-stampede-dev
