newversion:
  commands:
    - npm --no-git-tag-version version $1
    - npm install
  description: Update the package.json with a new version
version:
  command: npm view stampede-server version
  description: Show the current version of the package
runlocal:
  command: bin/stampede-server.js --config .stampederc-local
  description: Run the stampede server against a local instance of redis/postgres running in docker
rungithub:
  command: bin/stampede-server.js --config .stampederc-github
  description: Run the stampede server against a local instance of redis/postgres running in docker connected to github
runresponse:
  command: bin/stampede-server.js --config .stampederc-response
  description: Run the stampede server against a local instance of redis/postgres running in docker
dockerpush:
  commands:
    - docker build -t davidahouse/stampede-server .
    - docker push davidahouse/stampede-server
    - docker build -t davidahouse/stampede-server:$1 .
    - docker push davidahouse/stampede-server:$1
tailwind:
  command: npx tailwindcss build css/tailwind.css -o public/css/styles.css
  description: Update the styles.css with the latest tailwind installed
