redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 7766:7766
  environment:
    - NODE_ENV=development
    - PORT=7766
  command:
    sh -c 'npm i && node ./bin/stampede-server.js'
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache

