redis:
  image: redis
  container_name: stampede-server-redis
  expose:
    - 6379

app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 7766:7766
  links:
    - redis
  environment:
    stampede_redisHost: stampede-server-redis
